FROM java:8-jdk-alpine

ADD target/springbootdemo-0.0.1-SNAPSHOT.jar /opt/spring-boot/springbootdemo-0.0.1-SNAPSHOT.jar
WORKDIR /opt/spring-boo

CMD ["java", "-jar","/opt/spring-boot/springbootdemo-0.0.1-SNAPSHOT.jar"]


